version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: people-postgres-prod
    networks:
      - shared-network
    image: postgres:13-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - $PWD/data/postgres-prod:/var/lib/postgresql/data

  people-api:
    container_name: people-api-prod
    networks:
      - shared-network
    image: people-api-prod
    command: --spring.datasource.url=jdbc:postgresql://db:5432/people --spring.profiles.active=prod --logging.level.root=info --server.port=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy